[build]
builder = "NIXPACKS"
watchPatterns = ["frontend/src/**", "frontend/public/**"]
buildCommand = "cd frontend && npm run build"

[deploy]
numReplicas = 1
startCommand = "cd frontend && npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[serve]
port = 3000